apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xhpneqi8v-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xhpneqi8v-go 
  name: xhpneqi8v-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xhpneqi8v-go 
